### ISSUE TITLE
Figure out the best way to structure the folder src/

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox-date-annotator-example#10]
## Motivation

This example repository for NLP Sandbox Date Annotators should implement all the best practices that come to our mind. This repo is expected to be forked by the Developers who will use the NLP Sandbox. We could also make this repo available as a GH template.

A best practice is to promote a modular implementation of the Date Annotators and other NLP Tools.

I don't have much experience with the development of Python packages / programs. Would a structure like the one below make sense?

- _src/library_: Python library that implements the logic of the Date Annotator (and optionally publish it on PyPI?)
- _src/server_: A Python-Flask server that implements the NLP Sandbox OpenAPI spec of the Date Annotator and use the above library for the core business logic. The current content has been generated using `openapi-generator`.
- _src/cli_: A command line interface program for the library (optional)?

@thomasyu888 @jaeddy What do you think is the best way to achieve this?

**Comment by thomasyu888** [comment]
I know we discussed this, but here is an example repository that has the above: https://github.com/common-workflow-language/workflow-service. 

This is a python implementation though.  They put in the API service under `wes_service` and the client that can interact with the API in `wes_client`.   This way when you can publish the bundle as a package to pypi.  This package has two `cli` base commands:

`wes-server` and `wes-client`

**Comment by tschaffter** [comment]
@thomasyu888 I agree that the structure of this repository should primarily target the service implementation. Therefore, the service implementation will be stored in a folder named `server` located at the root of the repo.
